import assert from 'node:assert/strict';
import fs from 'node:fs';
const source = fs.readFileSync(new URL('../index.html', import.meta.url), 'utf8');
for (const marker of ['let missionRunToken = 0', 'nextQ(!!saved)', 'M.i++; savePausedMission(); lockThen(nextQ)', 'M.i++; savePausedMission(); lockThen(nextQ, 6500)', 'if (resetInProgress) return', 'if (!M || M.completed ||', 'const token=missionRunToken', 'if (token !== missionRunToken || !M) return', 'if (!M || M.completed) return', 'M.completed = true']) assert.match(source, new RegExp(marker.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')));
const paused = { alex: { player:'alex', i:3, attempts:2, answer:'3/4', bbLevel:2 }, katya:null };
assert.equal(paused.alex.player, 'alex');
assert.equal(paused.alex.i, 3);
assert.equal(paused.alex.attempts, 2);
assert.equal(paused.alex.answer, '3/4');
assert.equal(paused.alex.bbLevel, 2);
assert.equal(paused.katya, null);
let token = 1, current = { player:'alex' }, mutations = 0;
const delayed = tokenAtSchedule => { if (tokenAtSchedule !== token || !current) return; mutations++; };
token = 2; current = { player:'katya' }; delayed(1);
assert.equal(mutations, 0);
let completed = false, rewards = 0;
const complete = () => { if (completed) return; completed = true; rewards++; };
complete(); complete();
assert.equal(rewards, 1);
console.log('mission lifecycle regression checks passed');
